fix: Add RezPackage parameter in job template
aws-deadline/deadline-cloud-for-after-effects pull request #88
Opened 2024-12-28 05:04 UTC by eherozhao

### What was the problem/requirement? (What/Why)
We would like to add a RezPackages support for customers who would build ae as a Rez Package.
### What was the solution? (How)
Add a hidden job parameter in the template.json
### What is the impact of this change?
Customers with Rez AE pacakge and use the template. 
### How was this change tested?
Changed the queue environment with a RezPackages parameter and the aftereffects-24 was overridden then.
<img width="511" alt="image" src="https://github.com/user-attachments/assets/d660f6b9-84ca-4240-9b43-db8837c5a77f" />

### Was this change documented?
N/A
### Is this a breaking change?
N/A
----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-12-30 17:08 UTC, crowecawcaw requested changes

2024-12-30 17:08 UTC, crowecawcaw commented on dist/DeadlineCloudSubmitter_Assets/JobTemplate/template.json
> +            "description": "If a queue accepts this parameter, it will create a Rez environment from it."
I think this should be a separate PR since it's not related to JSON vs YAML.

It'd also help to introduce this change alongside a README update describing how to use it. I can't quite imagine how it's supposed to work. The screenshot where both conda and rez packages are displayed as inputs at the same time doesn't seem right at first glance.

2024-12-30 17:48 UTC, eherozhao commented on dist/DeadlineCloudSubmitter_Assets/JobTemplate/template.json
> +            "description": "If a queue accepts this parameter, it will create a Rez environment from it."
> The screenshot where both conda and rez packages are displayed as inputs at the same time doesn't seem right at first glance.

That is because I have both Conda Packages and Rez Pakcages in my QEnv.

2024-12-30 17:51 UTC, eherozhao commented on dist/DeadlineCloudSubmitter_Assets/JobTemplate/template.json
> +            "description": "If a queue accepts this parameter, it will create a Rez environment from it."
Thanks for your reply! I removed RezPackage change from this PR and will push a new PR related to this later.

2024-12-30 17:53 UTC, mwiebe commented on dist/DeadlineCloudSubmitter.jsx
> +                alert(paramDefCopy[i].default);
Something left over from debugging?

2024-12-30 17:56 UTC, eherozhao commented on dist/DeadlineCloudSubmitter.jsx
> +                alert(paramDefCopy[i].default);
Thanks for catching this, I have deleted it in the new revision.

2024-12-31 17:11 UTC, crowecawcaw requested changes

2024-12-31 17:11 UTC, crowecawcaw commented on src/submission/SubmitBundle.jsx
> +        const aftereffectsVersion = app.version[0] + app.version[1];
Do we need to add a `.` between the two version strings? What does the combined version look like?

2024-12-31 17:11 UTC, crowecawcaw commented on src/submission/SubmitBundle.jsx
> +        template.write(JSON.stringify(templateDict));
Small nicety: the JSON will be nicely formatted if you do `JSON.stringify(templateDict, null, 2)`

2024-12-31 17:11 UTC, crowecawcaw commented on src/submission/SubmitBundle.jsx
> +        var templateDict = JSON.parse(templateContents);
Super nit: JavaScript calls these "objects" instead of "dicts".

2024-12-31 17:11 UTC, crowecawcaw commented on src/submission/SubmitBundle.jsx
> +        const aftereffectsVersion = app.version[0] + app.version[1];
Also do we need to add a `*` to the end of the version string or have some sort of flexible version requirement? It looks like the version will be pegged to a single release.

2024-12-31 17:29 UTC, eherozhao commented on src/submission/SubmitBundle.jsx
> +        template.write(JSON.stringify(templateDict));
Oh, goot to know! Will update this.

2024-12-31 17:32 UTC, eherozhao commented on src/submission/SubmitBundle.jsx
> +        const aftereffectsVersion = app.version[0] + app.version[1];
Unfortunately we have to. The app.version[0] returned 2 and the next index returned 4 so the combination is version 24. It depends on if customer would like to use major version as the conda package version or also with a minor version.

I can keep this as a note and check if we would like to use major,minor version as the default conda package or just major version in the future. For now, I personally don't worry much about it.

2024-12-31 18:54 UTC, eherozhao commented on src/submission/SubmitBundle.jsx
> +        template.write(JSON.stringify(templateDict));
For sure. I can update this. Any thoughts on 4 spaces?

2024-12-31 19:05 UTC, viknith reviewed
QQ, does setting RezPackages in QE and then seeing it autofill in the GUI submitter follow the pattern that other submitters follow? Asking because of the prior conversation we had about not wanting to repeat the same behavior with the CondaPackages parameter. @eherozhao @mwiebe

2024-12-31 19:28 UTC, mwiebe approved these changes

2024-12-31 19:29 UTC, mwiebe commented
> QQ, does setting RezPackages in QE and then seeing it autofill in the GUI submitter follow the pattern that other submitters follow? Asking because of the prior conversation we had about not wanting to repeat the same behavior with the CondaPackages parameter. @eherozhao @mwiebe

@eherozhao is planning to make a follow-up PR that makes the pattern for Rez identical to Conda.

2024-12-31 20:19 UTC, crowecawcaw approved these changes

2024-12-31 20:19 UTC, merged